name: Outputting the values of default Github Builtin variable values
on:
 push:

jobs:
 Explore-Github-Defaultvariables:
  runs-on: ubuntu-latest
  steps: 
   - name: Printing the value of Github Actor
     run: |
      echo "The value of Github actor is: ${{github.actor}}"

   - name: Printing the value of github event
     run: |
       echo "The value of Github Event is: ${{github.event_name}}"
   - name: Pringinting the OS value
     run: |
      echo "The value of Operating System: ${{runner.os}}"
      echo "The vlaue of branch is: ${{github.ref}}"
      echo "The value of repository is: ${{github.repository}}"
      echo "The value of job status is: ${{job.status}}"
      ls ${{github.workspace}}
