name: A workflow for my demo website
on:
 push
jobs:
 build-job:
  name: Hello world action
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v1
  - name: Hello world
    run: echo Hello world
  - name: index.html content
    run: cat index.html
  
    
  
  
