name: A workflow for my own website
on:
 workflow_call
jobs:
 build-job:
  name: Printing html content
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v1
   - name: echo Hello World
     run: echo Hello World
   - name: Printing html content
     run: |
      cat index.html
      cat courses.html
  
  
