name: outputs_demo


on:
 workflow_dispatch:

jobs:
 job1:
  runs-on: ubuntu-latest

  outputs:
   output1: ${{ steps.step1.outputs.test }}
   output2: ${{ steps.step2.outputs.test }}

        steps:
          - name: outputs_demo
          - id: step1
            run: echo "::set-output name=test::Hello"
          - id: step2
            run: echo "::set-output name=test::World"  
            

          