name: testing purpose
on:
 push:

jobs:
 build-job:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4

   - name: list the files
     run: ls -a

   - name: AWS CLI list
     run: aws --version

   - name: Helloworld
     run: echo "This workflow is created just for testing purpose"
      
 
   
