name: testing purpose
on:
 workflow_dispatch:

jobs:
 build-job:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4

   - name: list the files
     run: ls -a

   - name: AWS CLI list
     run: aws --version
 
   