name: testing purpose
on:
  push:
   branches:
    - my_first_branch
   paths:
    - tests.yml

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List the files
        run: ls -a

      - name: AWS CLI version
        run: aws --version

      - name: Helloworld
        run: echo "This workflow is created just for testing purpose"

  Powershell-Execution:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Powershell script execution
        run: pwsh -File ./calculateTwoNumbers.ps1
