name: TestActions
on:
 push:

jobs:
 build:
  runs-on: ubutu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v2

   - name: Run a one-line script
     run: echo Hello, world!

   - name: Run a multi-line script
     run: |
       echo Add other actions to build,
       echo test, and deploy your project.
   
   -  name: install Phython
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
   -  name: Run Python script 
      run: |
        python3 test.py

 display1:
  runs-on: ubuntu-latest
  needs: build
  steps:
   - name: Checkout
     uses: actions/checkout@v2

   - name: Display the content of index.html
     run: |
       cat index.html

 display2:
  runs-on: ubuntu-latest
  needs: [build, display1]
  steps:
   - name: Checkout
     uses: actions/checkout@v2

   - name: Display the content of index.html
     run: |
       cat courses.html

 display3:
   runs-on: ubuntu-latest
   needs: [build, display1, display2]

   steps:
     - name: Checkout
       uses: actions/checkout@v2

     - name: Display the content of html
       run: |
          cat index.html
          cat courses.html
 
